line-length = 120
exclude = [
    "tests/",
    "build/",
    "docs/",
    ".venv/",
    "plugin/",  
    "MEMORY",
]

[lint]
select = ["E", "F", "W"]

ignore = [
    "W291", 
    "W292", 
    "W293", 
    "E402", 
    "E501", 
    "E502", 
    "F401", 
]
